import type { Metadata } from "next";

import "../globals.css";

import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";

import BGGradient from "@/components/ui/bg-gradient";
import { routing } from "@/i18n/routing";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
    params,
}: {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}) {
    const { locale } = await params;
    if (!hasLocale(routing.locales, locale)) {
        notFound();
    }

    return (
        <html lang={locale} dir={locale === "he" ? "rtl" : "ltr"} className="dark" suppressHydrationWarning>
            <body className="antialiased">
                <BGGradient />
                <NextIntlClientProvider>{children}</NextIntlClientProvider>
            </body>
        </html>
    );
}
